name: my_cashbook
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  firebase_storage: ^10.3.8
  provider: ^6.0.3
  path_provider: ^2.0.11
  flutter: 
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
  intl: ^0.17.0
  firebase_database: ^9.1.4
  api_cache_manager: ^1.0.2
  country_picker: ^2.0.16
  telephony: ^0.2.0
  otp_text_field: ^1.1.3
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.1
  local_auth: ^2.1.2
  fluttertoast: ^8.0.9
  flutter_contacts: ^1.1.5
  contacts_service: ^0.6.3
  permission_handler: ^10.0.1
  carousel_slider: ^4.1.1
  mobile_number: ^2.1.0
  duration_button: ^1.0.0
  pull_to_refresh: ^2.0.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/onBoarding/
    - assets/translations/
  generate: true
